In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_excel(r"C:\Users\user\OneDrive\Desktop\Thesis\Mortality\Mortality Data-translated into english 3 English Translated.xlsx")

In [8]:
data.columns[0:4]

Index(['Deaths date', 'District', 'Governorate', 'Death Count'], dtype='object')

In [10]:
data = data[data.columns[0:4]]

In [16]:
data['Governorate'].unique()

array(['Ajloun ', 'Amman ', 'Aqaba ', 'Balqa ', 'Gaza', 'Irbid ',
       'Jarash ', 'Karak', "Ma'an ", 'Madaba ', 'Mafraq ', 'Nablus',
       'Palestine 48', 'Tafiela ', 'Zarqa '], dtype=object)

In [17]:
data[data['Governorate'] == 'Amman ']['District'].unique()

array(['Jizeh              ', 'Amman Qasabah                ',
       'Marka               ', 'Wadi Essier          ',
       "Na'oor               ", 'Sahab                ',
       'Alquaismeh            ', "Al-Jami'ah             ",
       'Mowaqqar             ', 'Amman Qasabah        ',
       'Bedouin middle           '], dtype=object)

In [21]:
amm = data[(data['District'] == 'Amman Qasabah                ') | (data['District'] == 'Marka               ') | (data['District'] == "Al-Jami'ah             ")]

In [22]:
amm

      Deaths date                       District Governorate  Death Count
5685   2000-01-01  Amman Qasabah                      Amman            32
5686   2000-01-01           Marka                     Amman             2
5687   2001-01-01  Amman Qasabah                      Amman            31
5689   2002-01-01  Amman Qasabah                      Amman            21
5692   2003-01-01  Amman Qasabah                      Amman            23
...           ...                            ...         ...          ...
23338  2019-12-31  Amman Qasabah                      Amman            45
23340  2020-12-31  Amman Qasabah                      Amman            37
23342  2021-12-31  Amman Qasabah                      Amman            55
23344  2022-12-31  Amman Qasabah                      Amman            40
23345  1999-12-31  Amman Qasabah                      Amman            13

[9765 rows x 4 columns]

In [28]:
amm.groupby(amm.columns[0])['Death Count'].sum().to_excel('Amman.xlsx')

In [33]:
data

       Deaths date                 District Governorate  Death Count
0       2000-01-01            Ajlun Qasabah     Ajloun             1
1       2002-01-01            Ajlun Qasabah     Ajloun             1
2       2004-01-01            Ajlun Qasabah     Ajloun             2
3       2004-01-01  Kufranjah                   Ajloun             2
4       2005-01-01            Ajlun Qasabah     Ajloun             1
...            ...                      ...         ...          ...
146234  2021-12-31    Zarqa Qasabah              Zarqa            15
146235  2022-12-31     Russeifa                  Zarqa             3
146236  2022-12-31    Zarqa Qasabah              Zarqa             5
146237  1999-12-31     Russeifa                  Zarqa             4
146238  1999-12-31    Zarqa Qasabah              Zarqa             6

[146239 rows x 4 columns]

In [35]:
data[data['Governorate'] == 'Irbid ']['District'].unique()

array(['Aghwar Shamaliyah  ', 'Ramtha', 'Koorah              ',
       'Bani Obeid            ', 'Qasabah Irbid           ',
       'Mazar Shamali', 'Wastiyyah    ', 'Bani Kenanah          ',
       'Taybeh      '], dtype=object)

In [37]:
irb = data[data['District'] == 'Qasabah Irbid           ']

In [40]:
irb.groupby(irb.columns[0])['Death Count'].sum().to_excel('Irbid.xlsx')

In [41]:
data[data['Governorate'] == 'Zarqa ']['District'].unique()

array(['Russeifa            ', 'Zarqa Qasabah', 'Hashemiyah         ',
       'Zarqa Qasabah        '], dtype=object)

In [43]:
zar = data[(data['District'] == 'Zarqa Qasabah') | (data['District'] == 'Zarqa Qasabah        ')]

In [45]:
zar.groupby(zar.columns[0])['Death Count'].sum().to_excel('Zarqa.xlsx')