In [1]:
import pandas as pd
import numpy as np

In [2]:
amm = pd.read_csv('./Multi pollutant models/Amman.csv')
irb = pd.read_csv('./Multi pollutant models/Irbid.csv')
zar = pd.read_csv('./Multi pollutant models/Zarqa.csv')

In [3]:
amm.fillna('', inplace=True)
irb.fillna('', inplace=True)
zar.fillna('', inplace=True)

In [4]:
amm

,Pollutant,co-pollutant,beta,se,P_val,RR,inf,sup,IR10,inf10,sup10,significance
0,Single PM10,,0.000975,0.000296,0.001001,1.009802,1.003961,1.015676,0.980175,0.396135,1.567614,**
1,,NO2,0.001062,0.000307,0.000546,1.010681,1.004623,1.016775,1.068084,0.462314,1.677507,***
2,,SO2,0.001187,0.000328,0.000309,1.011938,1.005448,1.018470,1.193806,0.544811,1.846990,***
3,,NO2+SO2,0.001183,0.000329,0.000330,1.011898,1.005399,1.018438,1.189759,0.539872,1.843848,***
4,Single NO2,,-0.000478,0.001757,0.785750,0.995235,0.961552,1.030099,-0.476460,-3.844816,3.009892,
5,,PM10,-0.001992,0.001810,0.271303,0.980278,0.946109,1.015681,-1.972210,-5.389126,1.568109,
6,,SO2,-0.000961,0.002301,0.676289,0.990435,0.946751,1.036135,-0.956489,-5.324901,3.613487,
7,,PM10+SO2,-0.000580,0.002293,0.800428,0.994220,0.950528,1.039920,-0.578041,-4.947222,3.991972,
8,Single SO2,,0.000119,0.001640,0.942000,1.001194,0.969531,1.033891,0.119380,-3.046895,3.389058,
9,,PM10,-0.002659,0.001814,0.142769,0.973758,0.939751,1.008995,-2.624225,-6.024920,0.899533,
10,,NO2,0.000699,0.002148,0.744905,1.007014,0.965502,1.050311,0.701375,-3.449818,5.031051,
11,,PM10+NO2,-0.002302,0.002298,0.316505,0.977239,0.934201,1.022259,-2.276146,-6.579935,2.225914,

In [5]:
amm['IR10'].round(2).astype(str) + ' (' + amm['inf10'].round(2).astype(str) + '-' + amm['sup10'].round(2).astype(str) + ')' + amm['significance'].astype(str)

0       0.98 (0.4-1.57)**
1     1.07 (0.46-1.68)***
2     1.19 (0.54-1.85)***
3     1.19 (0.54-1.84)***
4      -0.48 (-3.84-3.01)
5      -1.97 (-5.39-1.57)
6      -0.96 (-5.32-3.61)
7      -0.58 (-4.95-3.99)
8       0.12 (-3.05-3.39)
9       -2.62 (-6.02-0.9)
10       0.7 (-3.45-5.03)
11     -2.28 (-6.58-2.23)
dtype: object

In [6]:
table = pd.DataFrame(columns=['Pollutant', 'co-pollutant', 'Amman', 'Irbid', 'Zarqa'])
table['Pollutant'] = amm['Pollutant']
table['co-pollutant'] = '+' + amm['co-pollutant']
table['Amman'] = amm['IR10'].round(2).astype(str) + ' (' + amm['inf10'].round(2).astype(str) + '-' + amm['sup10'].round(2).astype(str) + ')' + amm['significance'].astype(str)
table['Irbid'] = irb['IR10'].round(2).astype(str) + ' (' + irb['inf10'].round(2).astype(str) + '-' + irb['sup10'].round(2).astype(str) + ')' + irb['significance'].astype(str)
table['Zarqa'] = zar['IR10'].round(2).astype(str) + ' (' + zar['inf10'].round(2).astype(str) + '-' + zar['sup10'].round(2).astype(str) + ')' + zar['significance'].astype(str)

In [7]:
table

,Pollutant,co-pollutant,Amman,Irbid,Zarqa
0,Single PM10,+,0.98 (0.4-1.57)**,0.95 (-1.08-3.01),-0.43 (-1.7-0.84)
1,,+NO2,1.07 (0.46-1.68)***,0.72 (-1.42-2.91),-0.22 (-1.56-1.14)
2,,+SO2,1.19 (0.54-1.85)***,1.19 (-0.99-3.42),-0.43 (-1.75-0.92)
3,,+NO2+SO2,1.19 (0.54-1.84)***,1.17 (-1.1-3.5),-0.25 (-1.61-1.13)
4,Single NO2,+,-0.48 (-3.84-3.01),4.47 (-2.35-11.76),-1.48 (-8.47-6.04)
5,,+PM10,-1.97 (-5.39-1.57),3.62 (-3.72-11.52),-5.29 (-13.07-3.2)
6,,+SO2,-0.96 (-5.32-3.61),1.75 (-5.97-10.1),-1.97 (-10.09-6.87)
7,,+PM10+SO2,-0.58 (-4.95-3.99),0.24 (-7.93-9.14),-5.88 (-14.49-3.59)
8,Single SO2,+,0.12 (-3.05-3.39),2.22 (-5.17-10.18),-0.09 (-7.6-8.02)
9,,+PM10,-2.62 (-6.02-0.9),1.45 (-6.25-9.78),-1.34 (-9.73-7.82)
10,,+NO2,0.7 (-3.45-5.03),1.61 (-6.18-10.04),1.02 (-7.84-10.73)
11,,+PM10+NO2,-2.28 (-6.58-2.23),1.39 (-6.61-10.06),1.47 (-8.14-12.08)

In [10]:
table.to_excel('Table 3 multipollutant models results.xlsx', index=False)